"""Run a RoboStack task for one distribution of this repository.

    pixi run rs <distro> <task> [args...]
    pixi run rs jazzy generate-recipes
    pixi run rs jazzy build-one ros2-ros-workspace
    pixi run rs changed-distros --base origin/main      # for CI

Every distribution lives in distros/<distro>/ and only holds what is specific to
it (vinca.yaml, distro.yaml, patches, snapshot, ...). Everything else is shared
(shared/, tools/, .scripts/, .github/). Tasks run inside distros/<distro>/, after
preparing the generated files there:

- distros/<d>/tests/            copy of shared/tests (vinca looks for tests next to vinca.yaml)
- distros/<d>/vinca_pinning.yaml  shared/pinning/* + the pinning settings in distro.yaml
- distros/<d>/conda_build_config.yaml  rendered from vinca_pinning.yaml (`render-pinning`)
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DISTROS = ROOT / "distros"
SHARED = ROOT / "shared"
TOOLS = ROOT / "tools"
CONDA_FORGE = "https://prefix.dev/conda-forge"

# Files whose change affects every distribution (anything outside distros/).
PER_DISTRO_PREFIX = "distros/"


def distros() -> list[str]:
    return sorted(p.name for p in DISTROS.iterdir() if (p / "vinca.yaml").is_file())


def settings(distro: str) -> dict:
    import yaml  # not needed for changed-distros, which runs without pixi in CI

    return yaml.safe_load((DISTROS / distro / "distro.yaml").read_text()) or {}


def channel_url(distro: str) -> str:
    s = settings(distro)
    name = s.get("channel_name", f"robostack-{distro}")
    if s.get("upload_target", "prefix") == "prefix":
        return f"https://prefix.dev/{name}"
    return f"https://conda.anaconda.org/{name}"


def run(cmd: list[str], cwd: Path) -> int:
    print("+", " ".join(cmd), f"  (in {cwd.relative_to(ROOT)})", flush=True)
    return subprocess.run(cmd, cwd=cwd).returncode


# --------------------------------------------------------------------------- #
# generated files
# --------------------------------------------------------------------------- #
def vinca_pinning(distro: str) -> str:
    """shared/pinning/conda_forge.yaml + overrides.yaml, adjusted by distro.yaml.

    Shared override entries that the distribution overrides itself are left out
    together with the comment lines above them (comments carry the conda-build
    selectors, so this works on text, not on parsed YAML).
    """
    s = settings(distro)
    own = s.get("pinning_overrides") or {}
    out = [f"# Generated by `pixi run rs {distro} render-pinning` from shared/pinning/ and",
           f"# distros/{distro}/distro.yaml; edit those instead.", ""]
    if s.get("conda_forge_pinning_version"):
        out.append(f"conda_forge_pinning_version: {s['conda_forge_pinning_version']}")
        out.append("migrations:")
        out += [f"  - {m}" for m in s.get("conda_forge_migrations") or []]
    else:
        out += [l for l in (SHARED / "pinning" / "conda_forge.yaml").read_text().splitlines()
                if not l.startswith("#")]
    comments: list[str] = []
    skip = False
    for line in (SHARED / "pinning" / "overrides.yaml").read_text().splitlines():
        if line.startswith("#"):
            continue
        if line.startswith("  #"):
            comments.append(line)
        elif line.startswith("  ") and not line.startswith("   "):
            skip = line[2:].split(":")[0] in own
            if not skip:
                out += comments + [line]
            comments = []
        elif line.startswith("    "):
            if not skip:
                out.append(line)
        else:
            out.append(line)
    if own:
        out.append(f"  # ros-{distro} specific (distros/{distro}/distro.yaml)")
        for key, value in own.items():
            out.append(f"  {key}:")
            out += [f"    - {v}" for v in (value if isinstance(value, list) else [value])]
    return "\n".join(out) + "\n"


def render_tests(distro: str, dest: Path) -> None:
    """Copy shared/tests; *.jinja files are rendered for the distribution
    ([% if distro == "humble" %] ... [% endif %], [= distro =])."""
    import jinja2

    env = jinja2.Environment(
        block_start_string="[%", block_end_string="%]",
        variable_start_string="[=", variable_end_string="=]",
        comment_start_string="[#", comment_end_string="#]",
        keep_trailing_newline=True, trim_blocks=True, lstrip_blocks=True,
        undefined=jinja2.StrictUndefined,
    )
    for src in sorted((SHARED / "tests").rglob("*")):
        if not src.is_file():
            continue
        rel = src.relative_to(SHARED / "tests")
        target = dest / str(rel).removesuffix(".jinja")
        target.parent.mkdir(parents=True, exist_ok=True)
        if src.suffix == ".jinja":
            target.write_text(env.from_string(src.read_text()).render(distro=distro))
        else:
            shutil.copy2(src, target)


def prepare(distro: str) -> None:
    d = DISTROS / distro
    tests = d / "tests"
    if tests.exists():
        shutil.rmtree(tests)
    render_tests(distro, tests)
    (d / "vinca_pinning.yaml").write_text(vinca_pinning(distro))


# --------------------------------------------------------------------------- #
# tasks
# --------------------------------------------------------------------------- #
def rattler_build(distro: str, args: list[str], skip_existing: bool = True) -> list[str]:
    cmd = ["rattler-build", "build", "-m", "./conda_build_config.yaml",
           "-c", channel_url(distro), "-c", CONDA_FORGE, "--channel-priority", "disabled"]
    return cmd + (["--skip-existing"] if skip_existing else []) + args


def task(distro: str, name: str, args: list[str]) -> int:
    d = DISTROS / distro
    py = [sys.executable]
    if name == "prepare":
        prepare(distro)
        return 0
    if name == "render-pinning":
        prepare(distro)
        return run(["vinca-pinning-render"], d)
    if name == "generate-recipes":
        prepare(distro)
        shutil.rmtree(d / "recipes", ignore_errors=True)
        shutil.rmtree(d / "recipes_only_patch", ignore_errors=True)
        (d / "recipes").mkdir()
        return run(["vinca", "-m", *args], d)
    if name == "check-orphaned-patches":
        return run(py + [str(TOOLS / "check_orphaned_platform_patches.py"), *args], d)
    if name == "check-patches":
        return run(py + [str(TOOLS / "check_patches_clean_apply.py"), *args], d)
    if name == "check-deps":
        return run(py + [str(TOOLS / "check_dependency_compat.py"), *args], d)
    if name == "gap-report":
        return run(py + [str(TOOLS / "build_gap_report.py"), *args], d)
    if name == "create-snapshot":
        return run(["vinca-snapshot", "-d", distro, "-o", "rosdistro_snapshot.yaml", *args], d)
    if name == "build":
        return run(rattler_build(distro, ["--recipe-dir", "./recipes", *args]), d)
    if name == "build-ci":  # used by .scripts/build_unix.sh / build_win.bat
        return run(rattler_build(distro, args, skip_existing=False), d)
    if name == "build-one":
        pkg = args[0] if args else "ros2-ros-workspace"
        for patch in (d / "patch").glob(f"{pkg}.*patch"):
            shutil.copy(patch, d / "recipes" / pkg / "patch" / patch.name)
        return run(rattler_build(distro, ["--recipe", f"./recipes/{pkg}/recipe.yaml", *args[1:]], False), d)
    if name == "upload":
        s = settings(distro)
        name_ = s.get("channel_name", f"robostack-{distro}")
        if s.get("upload_target", "prefix") == "prefix":
            cmd = ["rattler-build", "upload", "prefix", "-c", name_, "--generate-attestation", "--skip-existing"]
        else:
            cmd = ["rattler-build", "upload", "anaconda", "-o", name_, "-a", os.environ.get("ANACONDA_API_TOKEN", ""), "--force"]
        return run(cmd + args, d)
    if name == "sort":
        files = ["pkg_additional_info.yaml", "rosdistro_additional_recipes.yaml"]
        rc = run(["vinca-sort-vinca-lists", *args, "vinca.yaml"], d)
        return rc or run(["vinca-sort-yaml-keys", *args, *files], d)
    if name == "gha":  # staged build workflows for one platform, see .github/workflows/main.yml
        return generate_gha(distro, args)
    raise SystemExit(f"unknown task {name!r}")


def generate_gha(distro: str, args: list[str]) -> int:
    """vinca-gha for one distribution; the workflow gets a distro-specific name,
    trigger branch and file name, and tells the build scripts which distro to build."""
    parser = argparse.ArgumentParser(prog="rs <distro> gha")
    parser.add_argument("--platform", required=True)
    parser.add_argument("--batch-size", default="10")
    ns = parser.parse_args(args)
    d = DISTROS / distro
    branch = f"buildbranch_{distro}_{ns.platform.replace('-', '_')}"
    before = set(d.glob("*.yml"))
    rc = run(["vinca-gha", "--platform", ns.platform, "--trigger-branch", branch, "-d", "./recipes",
              "--batch_size", ns.batch_size], d)
    if rc:
        return rc
    import yaml

    for wf in sorted(set(d.glob("*.yml")) - before):
        data = yaml.safe_load(wf.read_text())
        data["name"] = f"{distro} {data.get('name', wf.stem)}"
        data["env"] = {**(data.get("env") or {}), "ROBOSTACK_DISTRO": distro}
        dest = ROOT / ".github" / "workflows" / f"build_{distro}_{wf.stem}.yml"
        dest.write_text(yaml.safe_dump(data, sort_keys=False, width=1000))
        wf.unlink()
        print(f"wrote {dest.relative_to(ROOT)} (trigger branch {branch})")
    return 0


def changed_distros(base: str) -> list[str]:
    out = subprocess.run(["git", "diff", "--name-only", f"{base}...HEAD"], cwd=ROOT,
                         capture_output=True, text=True, check=True).stdout.split()
    out = [f for f in out if not f.endswith(".md") and f != "LICENSE"]  # docs don't need builds
    if any(not f.startswith(PER_DISTRO_PREFIX) for f in out):
        return distros()  # shared files changed: every distribution is affected
    return sorted({f.split("/")[1] for f in out if f.count("/") >= 2} & set(distros()))


def main() -> int:
    if len(sys.argv) >= 2 and sys.argv[1] == "changed-distros":
        parser = argparse.ArgumentParser(prog="rs changed-distros")
        parser.add_argument("--base", required=True)
        parser.add_argument("--all", action="store_true", help="ignore the diff, list every distribution")
        ns = parser.parse_args(sys.argv[2:])
        print(json.dumps(distros() if ns.all else changed_distros(ns.base)))
        return 0
    if len(sys.argv) < 3:
        print(__doc__)
        print("distributions:", ", ".join(distros()))
        return 2
    distro, name, *args = sys.argv[1:]
    if distro not in distros():
        raise SystemExit(f"unknown distribution {distro!r}; choose from {', '.join(distros())}")
    return task(distro, name, args)


if __name__ == "__main__":
    sys.exit(main())
