"""Run a RoboStack task for one distribution of this repository.

    pixi run rs <distro> <task> [args...]
    pixi run rs jazzy generate-recipes
    pixi run rs jazzy build-one ros2-ros-workspace
    pixi run rs changed-distros --base origin/main      # for CI
    pixi run rs check | update-pinning | new-distro NAME --from DISTRO   (whole repository)
    pixi run rs <distro> update-pinning                                  (one distribution)

Every distribution lives in distros/<distro>/ and only holds what is specific to
it; everything else is in shared/. distros/<d>/vinca.yaml extends shared/vinca.yaml,
and vinca combines both and the files next to each (pkg_additional_info.yaml,
patch/ with dependencies.yaml, tests/, robostack.yaml). Tasks run in
distros/<distro>/work/ (generated, git-ignored): its vinca.yaml extends the
distribution's and adds the channel to skip published packages, and it holds
vinca_pinning.yaml, conda_build_config.yaml (rendered back into distros/<d>/ by
`render-pinning`), .scripts/ and the generated recipes/ and output/.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DISTROS = ROOT / "distros"
SHARED = ROOT / "shared"
TOOLS = ROOT / "tools"
CONDA_FORGE = "https://prefix.dev/conda-forge"

# Files whose change affects every distribution (anything outside distros/).
PER_DISTRO_PREFIX = "distros/"


def distros() -> list[str]:
    return sorted(p.name for p in DISTROS.iterdir() if (p / "vinca.yaml").is_file())


def settings(distro: str) -> dict:
    import yaml  # not needed for changed-distros, which runs without pixi in CI

    return yaml.safe_load((DISTROS / distro / "distro.yaml").read_text()) or {}


def channel_url(distro: str) -> str:
    s = settings(distro)
    name = s.get("channel_name", f"robostack-{distro}")
    if s.get("upload_target", "prefix") == "prefix":
        return f"https://prefix.dev/{name}"
    return f"https://conda.anaconda.org/{name}"


def run(cmd: list[str], cwd: Path) -> int:
    print("+", " ".join(cmd), f"  (in {cwd.relative_to(ROOT)})", flush=True)
    return subprocess.run(cmd, cwd=cwd).returncode


# prefix.dev's sharded repodata (what rattler reads) lists a new upload a few minutes
# after repodata.json does, so a stage that starts right after the previous one
# uploaded can find no candidates for a package that is on the channel.
INDEX_LAG_MESSAGE = b"No candidates were found"
INDEX_LAG_RETRIES = 2
INDEX_LAG_WAIT = 180


def run_build(cmd: list[str], cwd: Path) -> int:
    """run() for staged builds: retry when the solver misses a package, waiting for
    the channel's index to catch up with the previous stage's uploads."""
    for attempt in range(INDEX_LAG_RETRIES + 1):
        print("+", " ".join(cmd), f"  (in {cwd.relative_to(ROOT)})", flush=True)
        missing = False
        with subprocess.Popen(cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT) as proc:
            for line in proc.stdout:
                sys.stdout.buffer.write(line)
                sys.stdout.buffer.flush()
                missing = missing or INDEX_LAG_MESSAGE in line
        if proc.returncode == 0 or not missing or attempt == INDEX_LAG_RETRIES:
            return proc.returncode
        print(f"A dependency was not found; waiting {INDEX_LAG_WAIT} s for the channel index "
              f"(retry {attempt + 1} of {INDEX_LAG_RETRIES})", file=sys.stderr, flush=True)
        time.sleep(INDEX_LAG_WAIT)
    return proc.returncode


# --------------------------------------------------------------------------- #
# generated files
# --------------------------------------------------------------------------- #
def vinca_pinning(distro: str) -> str:
    """shared/pinning/conda_forge.yaml + overrides.yaml, adjusted by distro.yaml.

    Shared override entries that the distribution overrides itself are left out
    together with the comment lines above them (comments carry the conda-build
    selectors, so this works on text, not on parsed YAML).
    """
    s = settings(distro)
    own = s.get("pinning_overrides") or {}
    out = [f"# Generated by `pixi run rs {distro} render-pinning` from shared/pinning/ and",
           f"# distros/{distro}/distro.yaml; edit those instead.", ""]
    if s.get("conda_forge_pinning_version"):
        out.append(f"conda_forge_pinning_version: {s['conda_forge_pinning_version']}")
        out.append("migrations:")
        out += [f"  - {m}" for m in s.get("conda_forge_migrations") or []]
    else:
        out += [l for l in (SHARED / "pinning" / "conda_forge.yaml").read_text().splitlines()
                if not l.startswith("#")]
    comments: list[str] = []
    skip = False
    for line in (SHARED / "pinning" / "overrides.yaml").read_text().splitlines():
        if line.startswith("#"):
            continue
        if line.startswith("  #"):
            comments.append(line)
        elif line.startswith("  ") and not line.startswith("   "):
            skip = line[2:].split(":")[0] in own
            if not skip:
                out += comments + [line]
            comments = []
        elif line.startswith("    "):
            if not skip:
                out.append(line)
        else:
            out.append(line)
    if own:
        out.append(f"  # ros-{distro} specific (distros/{distro}/distro.yaml)")
        for key, value in own.items():
            out.append(f"  {key}:")
            out += [f"    - {v}" for v in (value if isinstance(value, list) else [value])]
    return "\n".join(out) + "\n"


def load_yaml(path: Path) -> dict:
    import yaml

    return (yaml.safe_load(path.read_text()) or {}) if path.is_file() else {}


def _constraint_name(spec: str) -> str:
    return re.split(r"[\s=<>!~]", str(spec).strip(), maxsplit=1)[0]


# package lists of vinca.yaml (import_distro strips the shared entries)
LIST_KEYS = ("packages_select_by_deps", "packages_exclude", "packages_skip")


def work_dir(distro: str) -> Path:
    return DISTROS / distro / "work"


def prepare(distro: str) -> Path:
    """Set up distros/<d>/work/, where vinca and rattler-build run (recipes/ and
    output/ of earlier runs are kept). work/vinca.yaml extends the distribution's
    vinca.yaml, which extends shared/vinca.yaml (vinca combines them, and the files
    next to each: pkg_additional_info.yaml, patch/, tests/, robostack.yaml)."""
    d, w = DISTROS / distro, work_dir(distro)
    w.mkdir(exist_ok=True)
    # copies an earlier version of this script made; vinca would read them as part of
    # the configuration (work/ is the extending configuration's directory)
    for stale in ("patch", "tests"):
        shutil.rmtree(w / stale, ignore_errors=True)
    for stale in ("pkg_additional_info.yaml", "robostack.yaml", "packages_ignore.yaml", "packages-ignore.yaml"):
        (w / stale).unlink(missing_ok=True)
    (w / "vinca.yaml").write_text(
        f"# Generated by `pixi run rs {distro} prepare`; edit distros/{distro}/vinca.yaml or shared/vinca.yaml.\n"
        "extends: ../vinca.yaml\n"
        f"skip_existing:\n  - {channel_url(distro)}/\n"
    )
    # vinca-gha inlines ./.scripts/build_win.bat into the Windows workflow
    shutil.rmtree(w / ".scripts", ignore_errors=True)
    shutil.copytree(ROOT / ".scripts", w / ".scripts")
    (w / "vinca_pinning.yaml").write_text(vinca_pinning(distro))
    if (d / "conda_build_config.yaml").is_file():
        shutil.copy2(d / "conda_build_config.yaml", w / "conda_build_config.yaml")
    return w


def read_vinca(distro: str, platform: str | None = None) -> dict:
    """The distribution's vinca configuration as vinca reads it (shared/ + distro,
    selectors resolved for the platform, default: this machine's)."""
    from vinca.configuration import read_vinca_yaml
    from vinca.platforms import get_conda_subdir

    return read_vinca_yaml(prepare(distro) / "vinca.yaml", platform or get_conda_subdir())


# --------------------------------------------------------------------------- #
# tasks
# --------------------------------------------------------------------------- #
def upload_channel_url() -> str | None:
    """The prefix.dev channel ROBOSTACK_UPLOAD_CHANNEL redirects uploads to, if any."""
    override = os.environ.get("ROBOSTACK_UPLOAD_CHANNEL", "").strip()
    if not override or override == "none":
        return None
    # repo.prefix.dev serves namespaced channels (owner/channel) directly
    return f"https://repo.prefix.dev/{override}"


def rattler_build(distro: str, args: list[str], skip_existing: bool = True) -> list[str]:
    # With uploads redirected (e.g. to a test channel), later stages of the staged
    # build need the packages earlier stages uploaded there, and reruns skip them.
    extra = upload_channel_url()
    cmd = ["rattler-build", "build", "-m", "./conda_build_config.yaml",
           *(["-c", extra] if extra else []),
           "-c", channel_url(distro), "-c", CONDA_FORGE, "--channel-priority", "disabled"]
    return cmd + (["--skip-existing"] if skip_existing else []) + args


def upload(distro: str, files: list[str], cwd: Path) -> int:
    """Upload to the distribution's channel.

    ROBOSTACK_UPLOAD_CHANNEL (set by the staged build workflows from the repository
    variable of the same name) redirects uploads to another prefix.dev channel, e.g.
    a test channel (the builds then also read from it, see rattler_build); "none"
    skips uploading. prefix.dev uploads use trusted publishing
    (with an attestation), or the PREFIX_API_KEY secret if it is set.
    """
    override = os.environ.get("ROBOSTACK_UPLOAD_CHANNEL", "").strip()
    if override == "none":
        print(f"ROBOSTACK_UPLOAD_CHANNEL=none: not uploading {' '.join(files)}")
        return 0
    s = settings(distro)
    if override or s.get("upload_target", "prefix") == "prefix":
        channel = override or s.get("channel_name", f"robostack-{distro}")
        cmd = ["rattler-build", "upload", "prefix", "-c", channel, "--skip-existing"]
        if not os.environ.get("PREFIX_API_KEY"):
            # the build workflows pass the secret through; without it the variable is
            # set but empty, and rattler-build would still take it for an API key
            # ("--generate-attestation cannot be used with an API key")
            os.environ.pop("PREFIX_API_KEY", None)
            cmd.append("--generate-attestation")
    else:
        token = os.environ.get("ANACONDA_API_TOKEN", "")
        cmd = ["rattler-build", "upload", "anaconda", "-o", s.get("channel_name", f"robostack-{distro}"), "-a", token, "--force"]
    # Sigstore (attestations) and the channels fail now and then; uploads are
    # idempotent (--skip-existing / --force), so retry.
    for attempt in range(1, 4):
        rc = run(cmd + files, cwd)
        if rc == 0 or attempt == 3:
            return rc
        print(f"upload attempt {attempt} failed, retrying in {30 * attempt} s", file=sys.stderr)
        time.sleep(30 * attempt)
    return rc


def task(distro: str, name: str, args: list[str]) -> int:
    d, w = DISTROS / distro, work_dir(distro)
    py = [sys.executable]
    if name == "prepare":
        prepare(distro)
        return 0
    if name == "render-pinning":
        prepare(distro)
        rc = run(["vinca-pinning-render"], w)
        if not rc:
            shutil.copy2(w / "conda_build_config.yaml", d / "conda_build_config.yaml")
        return rc
    if name == "create-snapshot":
        return run(["vinca-snapshot", "-d", distro, "-o", "rosdistro_snapshot.yaml", *args], d)
    if name == "sort":
        files = [f for f in ("pkg_additional_info.yaml", "rosdistro_additional_recipes.yaml") if (d / f).is_file()]
        rc = run(["vinca-sort-vinca-lists", *args, "vinca.yaml"], d)
        return rc or run(["vinca-sort-yaml-keys", *args, *files], d)
    if name == "upload":
        return upload(distro, args, w if w.is_dir() else d)
    if name in ("update-snapshot", "find-stale", "update-pinning"):
        import maintenance

        return maintenance.main(name, args, distro)

    # everything else runs in the assembled work directory
    if name == "generate-recipes":
        prepare(distro)
        shutil.rmtree(w / "recipes", ignore_errors=True)
        shutil.rmtree(w / "recipes_only_patch", ignore_errors=True)
        (w / "recipes").mkdir()
        return run(["vinca", "-m", *args], w)
    if not (w / "vinca.yaml").is_file():
        prepare(distro)
    if name == "check-orphaned-patches":
        return run(py + [str(TOOLS / "check_orphaned_platform_patches.py"), "--patch-dir", str(d / "patch"), *args], w)
    if name == "check-patches":
        return run(py + [str(TOOLS / "check_patches_clean_apply.py"), "--patch-dir", str(d / "patch"), *args], w)
    if name == "check-deps":
        return run(py + [str(TOOLS / "check_dependency_compat.py"), *args], w)
    if name == "gap-report":
        return run(py + [str(TOOLS / "build_gap_report.py"), *args], w)
    if name == "build":
        return run(rattler_build(distro, ["--recipe-dir", "./recipes", *args]), w)
    if name == "build-ci":  # used by .scripts/build_unix.sh / build_win.bat
        return run_build(rattler_build(distro, args, skip_existing=False), w)
    if name == "build-one":
        pkg = args[0] if args else "ros2-ros-workspace"
        for patch in (d / "patch").glob(f"{pkg}.*patch"):
            shutil.copy(patch, w / "recipes" / pkg / "patch" / patch.name)
        return run(rattler_build(distro, ["--recipe", f"./recipes/{pkg}/recipe.yaml", *args[1:]], False), w)
    if name == "gha":  # staged build workflows for one platform, see .github/workflows/main.yaml
        return generate_gha(distro, args)
    raise SystemExit(f"unknown task {name!r}")


def generate_gha(distro: str, args: list[str]) -> int:
    """vinca-gha for one distribution; the workflow gets a distro-specific name and
    trigger branch, the file name .github/workflows/build.yaml, and tells the build
    scripts which distro to build."""
    parser = argparse.ArgumentParser(prog="rs <distro> gha")
    parser.add_argument("--platform", required=True)
    parser.add_argument("--batch-size", default="25")
    ns = parser.parse_args(args)
    d = work_dir(distro)
    branch = f"buildbranch_{distro}_{ns.platform.replace('-', '_')}"
    before = set(d.glob("*.yml"))
    rc = run(["vinca-gha", "--platform", ns.platform, "--trigger-branch", branch, "-d", "./recipes",
              "--batch_size", ns.batch_size], d)
    if rc:
        return rc
    # Edit the text: a YAML round trip would turn the `on:` key into `true:` (YAML 1.1).
    for wf in sorted(set(d.glob("*.yml")) - before):
        lines = wf.read_text().splitlines()
        # all build branches share .github/workflows/build.yaml, which GitHub lists as one
        # workflow: run-name tells the runs apart
        lines = [f"name: build\nrun-name: {distro} {ns.platform}" if l.startswith("name: ") else l for l in lines]
        if ns.platform == "win-64" and not any("build-ci" in l for l in lines):
            raise SystemExit(f"{wf}: the Windows workflow doesn't use .scripts/build_win.bat")
        if any(l.startswith("env:") for l in lines):
            raise SystemExit(f"{wf}: unexpected top-level env in the vinca-gha output")
        lines += [
            "env:",
            f"  ROBOSTACK_DISTRO: {distro}",
            "  # optional repository variable: upload to this prefix.dev channel instead",
            "  # (e.g. a test channel), or 'none' to only build",
            "  ROBOSTACK_UPLOAD_CHANNEL: ${{ vars.ROBOSTACK_UPLOAD_CHANNEL }}",
            "  # optional secret: prefix.dev API key, for channels without Repository Access (OIDC)",
            "  PREFIX_API_KEY: ${{ secrets.PREFIX_API_KEY }}",
        ]
        # one file name on every build branch (each branch carries only its own
        # workflow), so a single prefix.dev Repository Access source matches them all
        dest = ROOT / ".github" / "workflows" / "build.yaml"
        dest.write_text("\n".join(lines) + "\n")
        wf.unlink()
        print(f"wrote {dest.relative_to(ROOT)} (trigger branch {branch})")
    return 0


def changed_distros(base: str) -> list[str]:
    # no common history (main's history was rewritten and force-pushed): nothing to
    # diff against, so every distribution counts as changed
    if subprocess.run(["git", "merge-base", base, "HEAD"], cwd=ROOT, capture_output=True).returncode:
        return distros()
    out = subprocess.run(["git", "diff", "--name-only", f"{base}...HEAD"], cwd=ROOT,
                         capture_output=True, text=True, check=True).stdout.split()
    out = [f for f in out if not f.endswith(".md") and f != "LICENSE"]  # docs don't need builds
    if any(not f.startswith(PER_DISTRO_PREFIX) for f in out):
        return distros()  # shared files changed: every distribution is affected
    return sorted({f.split("/")[1] for f in out if f.count("/") >= 2} & set(distros()))


REPO_COMMANDS = ("check", "update-pinning", "new-distro", "parse-command", "add-package", "rosdistro-syncs")


def main() -> int:
    if len(sys.argv) >= 2 and sys.argv[1] in REPO_COMMANDS:
        import maintenance

        return maintenance.main(sys.argv[1], sys.argv[2:])
    if len(sys.argv) >= 2 and sys.argv[1] == "changed-distros":
        parser = argparse.ArgumentParser(prog="rs changed-distros")
        parser.add_argument("--base", required=True)
        parser.add_argument("--all", action="store_true", help="ignore the diff, list every distribution")
        ns = parser.parse_args(sys.argv[2:])
        print(json.dumps(distros() if ns.all else changed_distros(ns.base)))
        return 0
    if len(sys.argv) < 3:
        print(__doc__)
        print("distributions:", ", ".join(distros()))
        return 2
    distro, name, *args = sys.argv[1:]
    if distro not in distros():
        raise SystemExit(f"unknown distribution {distro!r}; choose from {', '.join(distros())}")
    return task(distro, name, args)


if __name__ == "__main__":
    sys.exit(main())
