"""Run a RoboStack task for one distribution of this repository.

    pixi run rs <distro> <task> [args...]
    pixi run rs jazzy generate-recipes
    pixi run rs jazzy build-one ros2-ros-workspace
    pixi run rs changed-distros --base origin/main      # for CI
    pixi run rs check | update-pinning | new-distro NAME --from DISTRO   (whole repository)

Every distribution lives in distros/<distro>/ and only holds what is specific to
it; everything else is in shared/. Tasks run in distros/<distro>/work/ (generated,
git-ignored), which `prepare` assembles from both:

- vinca.yaml               shared/vinca.yaml + distros/<d>/vinca.yaml (lists are
                           concatenated, other keys from the distribution win)
- pkg_additional_info.yaml shared/ + distros/<d>/ (per package; the distribution's
                           keys win, e.g. its build_number)
- patch/                   distros/<d>/patch/, with patch/dependencies.yaml merged
                           from shared/dependencies.yaml like pkg_additional_info
- tests/                   shared/tests (*.jinja rendered for the distribution)
- robostack.yaml, packages-ignore.yaml, vinca_pinning.yaml, conda_build_config.yaml

rosdistro_snapshot.yaml and rosdistro_additional_recipes.yaml are read from
distros/<d>/ directly; conda_build_config.yaml is rendered back into distros/<d>/
(committed) by `render-pinning`.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DISTROS = ROOT / "distros"
SHARED = ROOT / "shared"
TOOLS = ROOT / "tools"
CONDA_FORGE = "https://prefix.dev/conda-forge"

# Files whose change affects every distribution (anything outside distros/).
PER_DISTRO_PREFIX = "distros/"


def distros() -> list[str]:
    return sorted(p.name for p in DISTROS.iterdir() if (p / "vinca.yaml").is_file())


def settings(distro: str) -> dict:
    import yaml  # not needed for changed-distros, which runs without pixi in CI

    return yaml.safe_load((DISTROS / distro / "distro.yaml").read_text()) or {}


def channel_url(distro: str) -> str:
    s = settings(distro)
    name = s.get("channel_name", f"robostack-{distro}")
    if s.get("upload_target", "prefix") == "prefix":
        return f"https://prefix.dev/{name}"
    return f"https://conda.anaconda.org/{name}"


def run(cmd: list[str], cwd: Path) -> int:
    print("+", " ".join(cmd), f"  (in {cwd.relative_to(ROOT)})", flush=True)
    return subprocess.run(cmd, cwd=cwd).returncode


# --------------------------------------------------------------------------- #
# generated files
# --------------------------------------------------------------------------- #
def vinca_pinning(distro: str) -> str:
    """shared/pinning/conda_forge.yaml + overrides.yaml, adjusted by distro.yaml.

    Shared override entries that the distribution overrides itself are left out
    together with the comment lines above them (comments carry the conda-build
    selectors, so this works on text, not on parsed YAML).
    """
    s = settings(distro)
    own = s.get("pinning_overrides") or {}
    out = [f"# Generated by `pixi run rs {distro} render-pinning` from shared/pinning/ and",
           f"# distros/{distro}/distro.yaml; edit those instead.", ""]
    if s.get("conda_forge_pinning_version"):
        out.append(f"conda_forge_pinning_version: {s['conda_forge_pinning_version']}")
        out.append("migrations:")
        out += [f"  - {m}" for m in s.get("conda_forge_migrations") or []]
    else:
        out += [l for l in (SHARED / "pinning" / "conda_forge.yaml").read_text().splitlines()
                if not l.startswith("#")]
    comments: list[str] = []
    skip = False
    for line in (SHARED / "pinning" / "overrides.yaml").read_text().splitlines():
        if line.startswith("#"):
            continue
        if line.startswith("  #"):
            comments.append(line)
        elif line.startswith("  ") and not line.startswith("   "):
            skip = line[2:].split(":")[0] in own
            if not skip:
                out += comments + [line]
            comments = []
        elif line.startswith("    "):
            if not skip:
                out.append(line)
        else:
            out.append(line)
    if own:
        out.append(f"  # ros-{distro} specific (distros/{distro}/distro.yaml)")
        for key, value in own.items():
            out.append(f"  {key}:")
            out += [f"    - {v}" for v in (value if isinstance(value, list) else [value])]
    return "\n".join(out) + "\n"


def render_tests(distro: str, dest: Path) -> None:
    """Copy shared/tests; *.jinja files are rendered for the distribution
    ([% if distro == "humble" %] ... [% endif %], [= distro =])."""
    import jinja2

    env = jinja2.Environment(
        block_start_string="[%", block_end_string="%]",
        variable_start_string="[=", variable_end_string="=]",
        comment_start_string="[#", comment_end_string="#]",
        keep_trailing_newline=True, trim_blocks=True, lstrip_blocks=True,
        undefined=jinja2.StrictUndefined,
    )
    for src in sorted((SHARED / "tests").rglob("*")):
        if not src.is_file():
            continue
        rel = src.relative_to(SHARED / "tests")
        target = dest / str(rel).removesuffix(".jinja")
        target.parent.mkdir(parents=True, exist_ok=True)
        if src.suffix == ".jinja":
            target.write_text(env.from_string(src.read_text()).render(distro=distro))
        else:
            shutil.copy2(src, target)


# vinca.yaml keys whose lists are combined from shared/ and the distribution
LIST_KEYS = ("packages_select_by_deps", "packages_skip_by_deps", "packages_remove_from_deps")


def load_yaml(path: Path) -> dict:
    import yaml

    return (yaml.safe_load(path.read_text()) or {}) if path.is_file() else {}


def dump_yaml(data: dict, path: Path, source: str) -> None:
    import yaml

    header = f"# Generated by `pixi run rs <distro> prepare` from {source}; edit those instead.\n"
    path.write_text(header + yaml.safe_dump(data, sort_keys=False, width=1000))


def merge_vinca(shared: dict, own: dict) -> dict:
    merged = dict(shared)
    for key, value in own.items():
        if key in LIST_KEYS:
            seen, items = set(), []
            for item in (shared.get(key) or []) + (value or []):
                marker = json.dumps(item, sort_keys=True)
                if marker not in seen:
                    seen.add(marker)
                    items.append(item)
            merged[key] = items
        else:
            merged[key] = value
    return merged


def merge_entries(shared: dict, own: dict) -> dict:
    """Per-package files: the distribution's keys of an entry win over the shared ones."""
    merged = {k: (dict(v) if isinstance(v, dict) else v) for k, v in shared.items()}
    for key, value in own.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = {**merged[key], **value}
        else:
            merged[key] = value
    return merged


def work_dir(distro: str) -> Path:
    return DISTROS / distro / "work"


def prepare(distro: str) -> Path:
    """Assemble distros/<d>/work/ (keeps recipes/ and output/ of earlier runs)."""
    d, w = DISTROS / distro, work_dir(distro)
    w.mkdir(exist_ok=True)
    for name in ("patch", "tests"):
        shutil.rmtree(w / name, ignore_errors=True)

    vinca = merge_vinca(load_yaml(SHARED / "vinca.yaml"), load_yaml(d / "vinca.yaml"))
    vinca.update(
        conda_index=["robostack.yaml", "packages-ignore.yaml"],
        patch_dir="patch",
        rosdistro_snapshot="../rosdistro_snapshot.yaml",
        rosdistro_additional_recipes="../rosdistro_additional_recipes.yaml",
    )
    vinca.setdefault("skip_existing", [channel_url(distro) + "/"])
    dump_yaml(vinca, w / "vinca.yaml", f"shared/vinca.yaml and distros/{distro}/vinca.yaml")
    dump_yaml(
        merge_entries(load_yaml(SHARED / "pkg_additional_info.yaml"), load_yaml(d / "pkg_additional_info.yaml")),
        w / "pkg_additional_info.yaml",
        f"shared/pkg_additional_info.yaml and distros/{distro}/pkg_additional_info.yaml",
    )
    shutil.copytree(d / "patch", w / "patch", ignore=shutil.ignore_patterns("dependencies.yaml"))
    dump_yaml(
        merge_entries(load_yaml(SHARED / "dependencies.yaml"), load_yaml(d / "patch" / "dependencies.yaml")),
        w / "patch" / "dependencies.yaml",
        f"shared/dependencies.yaml and distros/{distro}/patch/dependencies.yaml",
    )
    render_tests(distro, w / "tests")
    for name in ("robostack.yaml", "packages-ignore.yaml"):
        shutil.copy2(SHARED / name, w / name)
    # vinca-gha inlines ./.scripts/build_win.bat into the Windows workflow (and falls
    # back to an outdated built-in script without it)
    shutil.rmtree(w / ".scripts", ignore_errors=True)
    shutil.copytree(ROOT / ".scripts", w / ".scripts")
    (w / "vinca_pinning.yaml").write_text(vinca_pinning(distro))
    if (d / "conda_build_config.yaml").is_file():
        shutil.copy2(d / "conda_build_config.yaml", w / "conda_build_config.yaml")
    return w


# --------------------------------------------------------------------------- #
# tasks
# --------------------------------------------------------------------------- #
def rattler_build(distro: str, args: list[str], skip_existing: bool = True) -> list[str]:
    cmd = ["rattler-build", "build", "-m", "./conda_build_config.yaml",
           "-c", channel_url(distro), "-c", CONDA_FORGE, "--channel-priority", "disabled"]
    return cmd + (["--skip-existing"] if skip_existing else []) + args


def upload(distro: str, files: list[str], cwd: Path) -> int:
    """Upload to the distribution's channel.

    ROBOSTACK_UPLOAD_CHANNEL (set by the staged build workflows from the repository
    variable of the same name) redirects uploads to another prefix.dev channel, e.g.
    a test channel; "none" skips uploading.
    """
    override = os.environ.get("ROBOSTACK_UPLOAD_CHANNEL", "").strip()
    if override == "none":
        print(f"ROBOSTACK_UPLOAD_CHANNEL=none: not uploading {' '.join(files)}")
        return 0
    s = settings(distro)
    if override or s.get("upload_target", "prefix") == "prefix":
        channel = override or s.get("channel_name", f"robostack-{distro}")
        cmd = ["rattler-build", "upload", "prefix", "-c", channel, "--generate-attestation", "--skip-existing"]
    else:
        token = os.environ.get("ANACONDA_API_TOKEN", "")
        cmd = ["rattler-build", "upload", "anaconda", "-o", s.get("channel_name", f"robostack-{distro}"), "-a", token, "--force"]
    return run(cmd + files, cwd)


def task(distro: str, name: str, args: list[str]) -> int:
    d, w = DISTROS / distro, work_dir(distro)
    py = [sys.executable]
    if name == "prepare":
        prepare(distro)
        return 0
    if name == "render-pinning":
        prepare(distro)
        rc = run(["vinca-pinning-render"], w)
        if not rc:
            shutil.copy2(w / "conda_build_config.yaml", d / "conda_build_config.yaml")
        return rc
    if name == "create-snapshot":
        return run(["vinca-snapshot", "-d", distro, "-o", "rosdistro_snapshot.yaml", *args], d)
    if name == "sort":
        files = [f for f in ("pkg_additional_info.yaml", "rosdistro_additional_recipes.yaml") if (d / f).is_file()]
        rc = run(["vinca-sort-vinca-lists", *args, "vinca.yaml"], d)
        return rc or run(["vinca-sort-yaml-keys", *args, *files], d)
    if name == "upload":
        return upload(distro, args, w if w.is_dir() else d)
    if name in ("update-snapshot", "find-stale"):
        import maintenance

        return maintenance.main(name, args, distro)

    # everything else runs in the assembled work directory
    if name == "generate-recipes":
        prepare(distro)
        shutil.rmtree(w / "recipes", ignore_errors=True)
        shutil.rmtree(w / "recipes_only_patch", ignore_errors=True)
        (w / "recipes").mkdir()
        return run(["vinca", "-m", *args], w)
    if not (w / "vinca.yaml").is_file():
        prepare(distro)
    if name == "check-orphaned-patches":
        return run(py + [str(TOOLS / "check_orphaned_platform_patches.py"), *args], w)
    if name == "check-patches":
        return run(py + [str(TOOLS / "check_patches_clean_apply.py"), *args], w)
    if name == "check-deps":
        return run(py + [str(TOOLS / "check_dependency_compat.py"), *args], w)
    if name == "gap-report":
        return run(py + [str(TOOLS / "build_gap_report.py"), *args], w)
    if name == "build":
        return run(rattler_build(distro, ["--recipe-dir", "./recipes", *args]), w)
    if name == "build-ci":  # used by .scripts/build_unix.sh / build_win.bat
        return run(rattler_build(distro, args, skip_existing=False), w)
    if name == "build-one":
        pkg = args[0] if args else "ros2-ros-workspace"
        for patch in (w / "patch").glob(f"{pkg}.*patch"):
            shutil.copy(patch, w / "recipes" / pkg / "patch" / patch.name)
        return run(rattler_build(distro, ["--recipe", f"./recipes/{pkg}/recipe.yaml", *args[1:]], False), w)
    if name == "gha":  # staged build workflows for one platform, see .github/workflows/main.yml
        return generate_gha(distro, args)
    raise SystemExit(f"unknown task {name!r}")


def generate_gha(distro: str, args: list[str]) -> int:
    """vinca-gha for one distribution; the workflow gets a distro-specific name,
    trigger branch and file name, and tells the build scripts which distro to build."""
    parser = argparse.ArgumentParser(prog="rs <distro> gha")
    parser.add_argument("--platform", required=True)
    parser.add_argument("--batch-size", default="10")
    ns = parser.parse_args(args)
    d = work_dir(distro)
    branch = f"buildbranch_{distro}_{ns.platform.replace('-', '_')}"
    before = set(d.glob("*.yml"))
    rc = run(["vinca-gha", "--platform", ns.platform, "--trigger-branch", branch, "-d", "./recipes",
              "--batch_size", ns.batch_size], d)
    if rc:
        return rc
    # Edit the text: a YAML round trip would turn the `on:` key into `true:` (YAML 1.1).
    for wf in sorted(set(d.glob("*.yml")) - before):
        lines = wf.read_text().splitlines()
        lines = [f"name: {distro} {l[6:]}" if l.startswith("name: ") else l for l in lines]
        if ns.platform == "win-64" and not any("build-ci" in l for l in lines):
            raise SystemExit(f"{wf}: the Windows workflow doesn't use .scripts/build_win.bat")
        if any(l.startswith("env:") for l in lines):
            raise SystemExit(f"{wf}: unexpected top-level env in the vinca-gha output")
        lines += [
            "env:",
            f"  ROBOSTACK_DISTRO: {distro}",
            "  # optional repository variable: upload to this prefix.dev channel instead",
            "  # (e.g. a test channel), or 'none' to only build",
            "  ROBOSTACK_UPLOAD_CHANNEL: ${{ vars.ROBOSTACK_UPLOAD_CHANNEL }}",
        ]
        dest = ROOT / ".github" / "workflows" / f"build_{distro}_{wf.stem}.yml"
        dest.write_text("\n".join(lines) + "\n")
        wf.unlink()
        print(f"wrote {dest.relative_to(ROOT)} (trigger branch {branch})")
    return 0


def changed_distros(base: str) -> list[str]:
    out = subprocess.run(["git", "diff", "--name-only", f"{base}...HEAD"], cwd=ROOT,
                         capture_output=True, text=True, check=True).stdout.split()
    out = [f for f in out if not f.endswith(".md") and f != "LICENSE"]  # docs don't need builds
    if any(not f.startswith(PER_DISTRO_PREFIX) for f in out):
        return distros()  # shared files changed: every distribution is affected
    return sorted({f.split("/")[1] for f in out if f.count("/") >= 2} & set(distros()))


REPO_COMMANDS = ("check", "update-pinning", "new-distro", "parse-command", "add-package")


def main() -> int:
    if len(sys.argv) >= 2 and sys.argv[1] in REPO_COMMANDS:
        import maintenance

        return maintenance.main(sys.argv[1], sys.argv[2:])
    if len(sys.argv) >= 2 and sys.argv[1] == "changed-distros":
        parser = argparse.ArgumentParser(prog="rs changed-distros")
        parser.add_argument("--base", required=True)
        parser.add_argument("--all", action="store_true", help="ignore the diff, list every distribution")
        ns = parser.parse_args(sys.argv[2:])
        print(json.dumps(distros() if ns.all else changed_distros(ns.base)))
        return 0
    if len(sys.argv) < 3:
        print(__doc__)
        print("distributions:", ", ".join(distros()))
        return 2
    distro, name, *args = sys.argv[1:]
    if distro not in distros():
        raise SystemExit(f"unknown distribution {distro!r}; choose from {', '.join(distros())}")
    return task(distro, name, args)


if __name__ == "__main__":
    sys.exit(main())
